### ISSUE TITLE
Kann noch ncihts nutzen - im Moment noch eine leere Seite

### ISSUE THREAD

**Issue by dergel** [tgoellner/redaxo5-treestructure#2]
Im Moment bekomme ich keine treestructure zu sehen .. Klicke ich auf das AddOn selbst kommt eine Seite auf der es so aussieht:

![bildschirmfoto 2016-02-12 um 00 47 51](https://cloud.githubusercontent.com/assets/322951/12994602/2fd3002c-d122-11e5-8a4a-438aea79f877.png)

und in der normalen Strukturansicht ist auch nichts zu sehen.

**Comment by tgoellner** [comment]
Wenn auch in der normalen Strukturansicht nichts zu sehen ist, dann sind wahrscheinlich noch keine Seiten und/oder Kategorien angelegt. Allerdings sollte hier zumindest die Root-Kategorie und Optionen zum Anlegen erscheinen - ich mach mal einen Bug aus diesem Issue.

**Comment by tgoellner** [comment]
In der aktuellen Version (1.0.1 beta) lassen sich nun auch bei leerem Root-Level Kategorien und Artikel anlegen.
